sudo: false
language: node_js
node_js:
  - '10'
branches:
  only:
    - develop
cache:
  directories:
    - node_modules
    - packages/frontend/node_modules
    - packages/lib3d/node_modules
    - packages/api/node_modules
    - packages/3d/node_modules
    - packages/ui/node_modules
    - packages/bloqs/node_modules
    - packages/junior/node_modules
    - $HOME/google-cloud-sdk

services:
  -docker

env:
  global:
  # Do not prompt for user input when using any SDK methods.
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - npm update
  - npm install -g lerna
  - npm install -g jest
install:
  - npm install
  - npx lerna bootstrap
script:
  - npm run tslint:prod
  - npm run test

# Deploy web version to Google Kubernetes Engine
after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./deploy-web.sh; fi

notifications:
    slack: bitbloq-developers:pFZJaDJIDsKSGqn4O0vJonrS
