---
- name: turn-led
  instructionType: statement
  category: component
  uiElements:
    - type: select
      parameterName: turnOn
      options:
        - value: true
          label: robotics.turn-on
        - value: false
          label: robotics.turn-off
    - type: label
      text: robotics.the-led

- name: if
  instructionType: block
  category: control
  uiElements:
    - type: label
      text: robotics.if
    - type: parameter
    - type: select
      parameterName: comparation
      options:
        - value: eq
          label: '='
        - value: neq
          label: '!='
        - value: gt
          label: '>'
        - value: gte
          label: '>='
        - value: lt
          label: '<'
        - value: lte
          label: '<='
    - type: parameter
    - type: label
      text: robotics.execute
