---
# ZumJunior
- name: zumjunior
  avrgirlBoard: zumjunior
  borndateBoard: zumjunior
  label: Zum Junior
  libraries:
    - zipURL: https://storage.googleapis.com/bitbloq-prod/arduino-libraries/BQZUMJunior.zip
      precompiled: true
  integrated:
    - component: zumjunior-rgb-led
      name: rgbLed
    - component: zumjunior-buzzer
      name: buzzer
  code:
    includes:
      - <BQZUMJunior.h>
      - <BQZUMJuniorPorts.h>
    globals:
      - BQ::ZUMJunior zumJunior;
    setup:
      - zumJunior.setup();

  image:
    url: https://storage.googleapis.com/bitbloq-prod/images/hardware/board/zumjunior.svg
  ports:
  - name: '1'
    connectorTypes:
    - zumjunior-digital
    - zumjunior-analog
    pins:
      - name: '0'
        value: BQ::ZUMJunior::ports[1][0]
      - name: '1'
        value: BQ::ZUMJunior::ports[1][1]
    position:
      x: -0.37
      y: -0.1
    width: 0.035
    height: 0.046
    direction: west
  - name: '2'
    connectorTypes:
    - zumjunior-digital
    - zumjunior-analog
    pins:
      - name: '0'
        value: BQ::ZUMJunior::ports[2][0]
      - name: '1'
        value: BQ::ZUMJunior::ports[2][1]
    position:
      x: -0.37
      y: 0.05
    width: 0.035
    height: 0.046
    direction: west
  - name: '3'
    connectorTypes:
    - zumjunior-digital
    - zumjunior-analog
    pins:
      - name: '0'
        value: BQ::ZUMJunior::ports[3][0]
      - name: '1'
        value: BQ::ZUMJunior::ports[3][1]
    position:
      x: 0.34
      y: 0.05
    width: 0.035
    height: 0.046
    direction: east
  - name: '4'
    connectorTypes:
      - zumjunior-digital
      - zumjunior-analog
    pins:
      - name: '0'
        value: BQ::ZUMJunior::ports[4][0]
      - name: '1'
        value: BQ::ZUMJunior::ports[4][1]
    position:
      x: 0.34
      y: -0.1
    width: 0.035
    height: 0.046
    direction: east
  - name: A
    connectorTypes:
      - zumjunior-digital
      - zumjunior-analog
      - zumjunior-i2c
    pins:
      - name: '0'
        value: BQ::ZUMJunior::ports[A][0]
      - name: '1'
        value: BQ::ZUMJunior::ports[A][1]
      - name: 'i2c'
        value: BQ::ZUMJunior::i2cPorts[A]
    position:
      x: 0.04
      y: -0.495
    width: 0.035
    height: 0.046
    direction: north
  - name: B
    connectorTypes:
      - zumjunior-digital
      - zumjunior-analog
      - zumjunior-i2c
    pins:
      - name: '0'
        value: BQ::ZUMJunior::ports[B][0]
      - name: '1'
        value: BQ::ZUMJunior::ports[B][1]
      - name: 'i2c'
        value: BQ::ZUMJunior::i2cPorts[B]
    position:
      x: -0.07
      y: -0.495
    width: 0.035
    height: 0.046
    direction: north

# ZumCore2
- name: zumcore2
  label: Zum Core 2.0
  image:
    url: https://storage.googleapis.com/bitbloq-prod/images/hardware/board/zumcore2.svg
  ports:
  - name: '23'
    connectorTypes:
    - digital
    position:
      x: -0.135
      y: -0.362
    width: 0.028
    height: 0.113
    direction: north
  - name: '22'
    connectorTypes:
    - digital
    position:
      x: -0.101
      y: -0.362
    width: 0.028
    height: 0.113
    direction: north
  - name: '13'
    connectorTypes:
    - digital
    position:
      x: -0.068
      y: -0.362
    width: 0.028
    height: 0.113
    direction: north

