---
# Generic components
- name: base-component
  code:
    globals:
      - >
        {% for connector in getComponentType(component).connectors %}
        {% for pin in connector.pins %}
        uint8_t {{component.name}}{{pin.name}} = {{getPinValue(component, connector.name, pin.portPin)}};
        {% endfor %}
        {% endfor %}

- name: digital-input
  extends: base-component
  code:
    setup:
      - >
        {% for connector in getComponentType(component).connectors %}
        {% for pin in connector.pins %}
        pinMode({{component.name}}{{pin.name}}, INPUT);
        {% endfor %}
        {% endfor %}

- name: digital-output
  extends: base-component
  code:
    setup:
      - >
        {% for connector in getComponentType(component).connectors %}
        {% for pin in connector.pins %}
        pinMode({{component.name}}{{pin.name}}, INPUT);
        {% endfor %}
        {% endfor %}

- name: button
  label: hardware.component.button
  instanceName: hardware.instanceName.button
  connectors:
  - name: main
    type: digital
    position:
      x: 0
      y: 1
    direction: south
  image:
    url: "https://storage.googleapis.com/bitbloq-prod/images/hardware/component/button.svg"
    width: 56
    height: 40

- name: joystick
  label: hardware.component.joystick
  instanceName: hardware.instanceName.joystick
  connectors:
  - name: kvg
    label: KVG
    type: digital
    position:
      x: 0
      y: -1
  - name: xvg
    label: XVG
    type: digital
    position:
      x: -0.4
      y: 1
  - name: yvg
    label: YVG
    type: digital
    position:
      x: 0.4
      y: 1
  image:
    url: "https://storage.googleapis.com/bitbloq-prod/images/hardware/component/joystick.svg"
    width: 68
    height: 54

# Zumjunior components
- name: zumjunior-rgb-led
  connectors: []

- name: zumjunior-buzzer
  connectors: []

- name: zumjunior-button
  extends: digital-input
  label: hardware.component.button
  instanceName: hardware.instanceName.button
  connectors:
    - name: main
      type: zumjunior-digital
      position:
        x: 0
        y: 1
      direction: south
      pins:
        - name: Pin
          portPin: '0'
  image:
    url: "https://storage.googleapis.com/bitbloq-prod/images/hardware/component/zumjunior_button.svg"
    width: 104
    height: 104

- name: zumjunior-7segment
  extends: base-component
  instanceName: hardware.instanceName.7segment
  libraries:
    - zipURL: https://storage.googleapis.com/bitbloq-prod/arduino-libraries/BQZUMI2C7SegmentDisplay.zip
      precompiled: true
  connectors:
    - name: main
      type: zumjunior-i2c
      position:
        x: 0
        y: 1
      pins:
        - name: i2c
          portPin: 'i2c'
  image:
    url: "https://storage.googleapis.com/bitbloq-prod/images/hardware/component/zumjunior_7segment.svg"
    width: 104
    height: 104
  code:
    includes:
      - <BQZUMI2C7SegmentDisplay.h>
    globals:
      - >
        BQ::ZUM::I2C7SegmentDisplay {{component.name}}Obj({{component.name}}i2c);
    setup:
      - >
        {{component.name}}Obj.setup();
        {{component.name}}Obj.displayChar(' ', ' ');

