---
- name: button
  label: hardware.component.button
  instanceName: hardware.instanceName.button
  connectors:
  - name: main
    type: digital
    position:
      x: 0
      y: 1
    direction: south
  image:
    url: "https://storage.googleapis.com/bitbloq-prod/images/hardware/component/button.svg"
    width: 56
    height: 40
- name: joystick
  label: hardware.component.joystick
  instanceName: hardware.instanceName.joystick
  connectors:
  - name: kvg
    label: KVG
    type: digital
    position:
      x: 0
      y: -1
  - name: xvg
    label: XVG
    type: digital
    position:
      x: -0.4
      y: 1
  - name: yvg
    label: YVG
    type: digital
    position:
      x: 0.4
      y: 1
  image:
    url: "https://storage.googleapis.com/bitbloq-prod/images/hardware/component/joystick.svg"
    width: 68
    height: 54

# Zumjunior components
- name: zumjunior-rgb-led
  connectors: []

- name: zumjunior-button
  label: hardware.component.button
  instanceName: hardware.instanceName.button
  connectors:
    - name: main
      type: zumjunior-digital
      position:
        x: 0
        y: 1
      direction: south
  image:
    url: "https://storage.googleapis.com/bitbloq-prod/images/hardware/component/zumjunior_button.svg"
    width: 104
    height: 104
